export const SCHEMA_VERSION = "dpa-keyword-foundation@0.1";

export const KEYWORD_CATEGORIES = Object.freeze([
  "MATERIAL",
  "OBLIGATION",
  "ACCESS",
  "DEPENDENCE",
  "KNOWLEDGE",
  "BELIEF",
  "EMOTION",
  "LEVERAGE",
]);

const projectProvenance = (keywordId) => ({
  sourceId: "project-keyword-core",
  sourceVersion: "0.1",
  sourceRecordId: keywordId,
  transformVersion: "keyword-normalizer@0.1",
  licenseId: "PROJECT_AUTHORED",
});

const keyword = (spec) => ({
  schemaVersion: SCHEMA_VERSION,
  inverseOrReciprocalRule: "No automatic inverse beyond the declared rule.",
  allowedEntityAndResourceTypes: ["ACTOR", "RESOURCE", "OBJECT", "LOCATION", "ACTION", "PROPOSITION", "SECRET", "OBLIGATION"],
  temporalityAndHistoryBehavior: "Active assertions are time-scoped; transitions emit history and never rewrite prior history.",
  negationDisputeAndBeliefHandling: "Negated, disputed, and belief-scoped assertions are distinct from actual asserted facts.",
  requiredAndForbiddenContexts: { required: [], forbidden: [] },
  relatedStats: [],
  compatibleKeywords: [],
  conflictingKeywords: [],
  possibleAffordances: { DEAL: [], PRESSURE: [], ASK: [] },
  blockersAndDefeaters: [],
  possibleHistoryEmissions: [],
  sourceAndProjectProvenance: [projectProvenance(spec.keywordId)],
  reviewStatus: "APPROVED",
  ...spec,
});

export const KEYWORDS = Object.freeze([
  keyword({
    keywordId: "OWNS",
    displayName: "Owns",
    definition: "An actor is the authored owner of a resource, object, or place.",
    explicitNonMeanings: ["Does not mean the actor currently possesses it.", "Does not mean the actor controls every access path."],
    category: "MATERIAL",
    arity: 2,
    typedArgumentRoles: { subject: "OWNER", object: "ASSET_OR_RESOURCE" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "OWNED_BY reverses subject and object; it is not symmetric.",
    allowedEntityAndResourceTypes: ["ACTOR", "RESOURCE", "OBJECT", "LOCATION"],
    relatedStats: ["control", "obligation"],
    compatibleKeywords: ["CONTROLS", "PERMITTED", "NEEDS"],
    conflictingKeywords: ["PROHIBITED"],
    possibleAffordances: { DEAL: ["OFFER_PARTIAL_PAYMENT"], PRESSURE: [], ASK: ["REQUEST_ACCESS"] },
    blockersAndDefeaters: ["ownership_expired", "explicit_transfer"],
    possibleHistoryEmissions: ["OWNERSHIP_TRANSFERRED"],
    positiveExamples: ["Marcus owns Apartment 305."],
    boundaryExamples: ["The player has keys but does not own Apartment 305."],
    counterexamples: ["A person standing beside an object owns it."],
  }),
  keyword({
    keywordId: "OWES",
    displayName: "Owes",
    definition: "A debtor has an authored obligation to transfer value or perform a specified return for a creditor.",
    explicitNonMeanings: ["Does not prove the debt is valid to every participant.", "Does not transfer money by itself."],
    category: "OBLIGATION",
    arity: 3,
    typedArgumentRoles: { subject: "DEBTOR", object: "CREDITOR", term: "OBLIGATION" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "IS_OWED_BY reverses debtor and creditor; the term remains time-scoped.",
    allowedEntityAndResourceTypes: ["ACTOR", "OBLIGATION", "RESOURCE"],
    temporalityAndHistoryBehavior: "Requires amount/unit/due condition; accepted, fulfilled, broken, and superseded transitions emit history.",
    relatedStats: ["obligation", "trust", "resentment", "leverage"],
    compatibleKeywords: ["NEEDS", "PROMISED_TO", "BELIEVES", "HAS_LEVERAGE_OVER"],
    conflictingKeywords: ["OWNS"],
    possibleAffordances: { DEAL: ["OFFER_PARTIAL_PAYMENT", "OFFER_CASH_FOR_EXTENSION"], PRESSURE: ["INVOKE_CONSEQUENCE"], ASK: ["REQUEST_EXTENSION", "CHALLENGE_DEBT_VALIDITY"] },
    blockersAndDefeaters: ["debt_fulfilled", "debt_expired", "debt_disputed_without_evidence"],
    possibleHistoryEmissions: ["DEBT_PROPOSED", "DEBT_RENEGOTIATED", "DEBT_FULFILLED", "DEBT_BROKEN"],
    positiveExamples: ["The player owes Marcus 250 USD due tomorrow morning."],
    boundaryExamples: ["Marcus claims the player owes him, but the authored ledger is disputed."],
    counterexamples: ["A request for help is not an OWES assertion."],
  }),
  keyword({
    keywordId: "NEEDS",
    displayName: "Needs",
    definition: "An actor has an active shortage or goal that makes a resource, permission, or state materially relevant.",
    explicitNonMeanings: ["Does not guarantee urgency or success.", "Does not state what the actor will choose."],
    category: "MATERIAL",
    arity: 2,
    typedArgumentRoles: { subject: "ACTOR", object: "RESOURCE_OR_STATE" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "No truth-preserving inverse; need is defeasible and actor-scoped.",
    allowedEntityAndResourceTypes: ["ACTOR", "RESOURCE", "PROPOSITION", "OBLIGATION"],
    relatedStats: ["dependence", "urgency_context"],
    compatibleKeywords: ["OWES", "DEPENDS_ON", "TRUSTS", "CONTROLS"],
    conflictingKeywords: ["OWNS"],
    possibleAffordances: { DEAL: ["OFFER_PARTIAL_PAYMENT"], PRESSURE: [], ASK: ["REQUEST_EXTENSION", "REQUEST_ACCESS"] },
    blockersAndDefeaters: ["need_satisfied", "resource_unavailable"],
    possibleHistoryEmissions: ["NEED_RECOGNIZED", "NEED_SATISFIED"],
    positiveExamples: ["The player needs an extension to keep the apartment."],
    boundaryExamples: ["The player prefers cash but does not need it to act."],
    counterexamples: ["A Vibe named Urgent does not create a NEEDS fact."],
  }),
  keyword({
    keywordId: "CONTROLS",
    displayName: "Controls",
    definition: "An actor has authored authority over access to a resource, place, or channel.",
    explicitNonMeanings: ["Does not mean ownership.", "Does not mean the actor will exercise control."],
    category: "ACCESS",
    arity: 2,
    typedArgumentRoles: { subject: "CONTROLLER", object: "RESOURCE_OR_ACCESS_CHANNEL" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "CONTROLLED_BY reverses controller and controlled object; it is not reciprocal by default.",
    allowedEntityAndResourceTypes: ["ACTOR", "RESOURCE", "LOCATION", "OBJECT"],
    relatedStats: ["control", "leverage"],
    compatibleKeywords: ["PERMITTED", "PROHIBITED", "OWNS", "DEPENDS_ON"],
    conflictingKeywords: [],
    possibleAffordances: { DEAL: ["OFFER_CASH_FOR_EXTENSION"], PRESSURE: ["INVOKE_CONSEQUENCE"], ASK: ["REQUEST_ACCESS"] },
    blockersAndDefeaters: ["control_revoked", "active_lock", "controller_unavailable"],
    possibleHistoryEmissions: ["ACCESS_GRANTED", "ACCESS_REVOKED"],
    positiveExamples: ["Marcus controls the Apartment 305 entry."],
    boundaryExamples: ["A tenant can enter a room without controlling the building lock."],
    counterexamples: ["Being physically near a door is not control."],
  }),
  keyword({
    keywordId: "PROMISED_TO",
    displayName: "Promised to",
    definition: "A promisor has made an authored commitment to a recipient for an action, resource, or condition.",
    explicitNonMeanings: ["Does not prove the promise was accepted.", "Does not guarantee fulfilment."],
    category: "OBLIGATION",
    arity: 3,
    typedArgumentRoles: { subject: "PROMISOR", object: "RECIPIENT", term: "COMMITMENT" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "HAS_PROMISE_FROM reverses the people but not the commitment's status.",
    allowedEntityAndResourceTypes: ["ACTOR", "RESOURCE", "ACTION", "OBLIGATION"],
    temporalityAndHistoryBehavior: "Promise status is historical and can be pending, fulfilled, broken, or superseded.",
    relatedStats: ["trust", "obligation", "resentment"],
    compatibleKeywords: ["OWES", "TRUSTS", "NEEDS"],
    conflictingKeywords: [],
    possibleAffordances: { DEAL: ["RENEGOTIATE_TERMS"], PRESSURE: ["INVOKE_CONSEQUENCE"], ASK: ["REQUEST_EXTENSION"] },
    blockersAndDefeaters: ["promise_expired", "recipient_not_known", "superseded_commitment"],
    possibleHistoryEmissions: ["PROMISE_MADE", "PROMISE_FULFILLED", "PROMISE_BROKEN"],
    positiveExamples: ["The player promised Marcus to pay the ledger term."],
    boundaryExamples: ["Saying 'maybe' is a proposal, not a promise."],
    counterexamples: ["A Vibe called Steadfast does not create PROMISED_TO."],
  }),
  keyword({
    keywordId: "PERMITTED",
    displayName: "Permitted",
    definition: "An authorized grant allows an actor to perform a typed action involving a resource or place under stated conditions.",
    explicitNonMeanings: ["Does not mean the action is physically possible.", "Does not override a more specific prohibition unless authored."],
    category: "ACCESS",
    arity: 3,
    typedArgumentRoles: { subject: "GRANTOR", object: "GRANTEE", term: "ACTION_OR_RESOURCE" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "PERMITS reverses grantor and grantee only as a capability record; it is not mutual.",
    allowedEntityAndResourceTypes: ["ACTOR", "ACTION", "RESOURCE", "LOCATION"],
    relatedStats: ["control", "trust", "respect"],
    compatibleKeywords: ["CONTROLS", "DEPENDS_ON", "OWNS"],
    conflictingKeywords: ["PROHIBITED"],
    possibleAffordances: { DEAL: ["OFFER_CASH_FOR_EXTENSION"], PRESSURE: [], ASK: ["REQUEST_ACCESS"] },
    blockersAndDefeaters: ["permission_expired", "active_lock", "specific_prohibition"],
    possibleHistoryEmissions: ["PERMISSION_GRANTED", "PERMISSION_REVOKED"],
    positiveExamples: ["Marcus permits the player to enter before the deadline."],
    boundaryExamples: ["A public door is not proof of a specific PERMITTED grant."],
    counterexamples: ["A polite request does not create permission."],
  }),
  keyword({
    keywordId: "PROHIBITED",
    displayName: "Prohibited",
    definition: "An authored authority or condition forbids a typed action for an actor or resource in a scope.",
    explicitNonMeanings: ["Does not itself prove the actor knows the prohibition.", "Does not establish a moral universal."],
    category: "ACCESS",
    arity: 3,
    typedArgumentRoles: { subject: "AUTHORITY", object: "ACTOR", term: "ACTION_OR_RESOURCE" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "PROHIBITS reverses authority and restricted actor as a rule reference; it is not symmetric.",
    allowedEntityAndResourceTypes: ["ACTOR", "ACTION", "RESOURCE", "LOCATION"],
    relatedStats: ["control", "fear", "resentment"],
    compatibleKeywords: ["CONTROLS", "FEARS", "HAS_LEVERAGE_OVER"],
    conflictingKeywords: ["PERMITTED"],
    possibleAffordances: { DEAL: [], PRESSURE: ["INVOKE_CONSEQUENCE"], ASK: ["CHALLENGE_DEBT_VALIDITY"] },
    blockersAndDefeaters: ["prohibition_revoked", "authorized_override", "authority_not_in_scope"],
    possibleHistoryEmissions: ["PROHIBITION_ISSUED", "PROHIBITION_LIFTED"],
    positiveExamples: ["Marcus prohibits entry after the lock is active."],
    boundaryExamples: ["A target's refusal is not the same as a world prohibition."],
    counterexamples: ["A character's fear does not automatically prohibit an action."],
  }),
  keyword({
    keywordId: "DEPENDS_ON",
    displayName: "Depends on",
    definition: "An actor or goal relies on a provider, resource, or condition for continued progress.",
    explicitNonMeanings: ["Does not guarantee affection or obedience.", "Does not force the provider to help."],
    category: "DEPENDENCE",
    arity: 2,
    typedArgumentRoles: { subject: "DEPENDENT", object: "PROVIDER_OR_RESOURCE" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "RELIED_ON_BY reverses the dependency; it is defeasible, not symmetric.",
    allowedEntityAndResourceTypes: ["ACTOR", "RESOURCE", "LOCATION", "OBLIGATION"],
    relatedStats: ["dependence", "trust", "leverage"],
    compatibleKeywords: ["NEEDS", "PERMITTED", "CONTROLS", "TRUSTS"],
    conflictingKeywords: [],
    possibleAffordances: { DEAL: ["OFFER_CASH_FOR_EXTENSION"], PRESSURE: ["INVOKE_CONSEQUENCE"], ASK: ["REQUEST_EXTENSION", "REQUEST_ACCESS"] },
    blockersAndDefeaters: ["provider_unavailable", "dependency_satisfied", "alternate_provider_authored"],
    possibleHistoryEmissions: ["DEPENDENCY_ESTABLISHED", "DEPENDENCY_BROKEN"],
    positiveExamples: ["The player's housing depends on Marcus's permission."],
    boundaryExamples: ["Wanting approval is not a material dependency."],
    counterexamples: ["A role label alone does not establish dependence."],
  }),
  keyword({
    keywordId: "KNOWS_SECRET_ABOUT",
    displayName: "Knows a secret about",
    definition: "A knower has scoped knowledge of confidential information concerning a subject.",
    explicitNonMeanings: ["Does not mean the secret is true unless actual evidence says so.", "Does not authorize disclosure."],
    category: "KNOWLEDGE",
    arity: 3,
    typedArgumentRoles: { subject: "KNOWER", object: "SECRET_SUBJECT", term: "SECRET" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "No naïve inverse; the subject need not know the knower has the secret.",
    allowedEntityAndResourceTypes: ["ACTOR", "SECRET", "PROPOSITION"],
    temporalityAndHistoryBehavior: "Knowledge has acquisition and exposure history; exposure can defeat secrecy but not erase prior knowledge.",
    negationDisputeAndBeliefHandling: "Actual knowledge, suspicion, and belief about another's knowledge remain separate scopes.",
    relatedStats: ["leverage", "trust", "fear"],
    compatibleKeywords: ["HAS_LEVERAGE_OVER", "BELIEVES", "FEARS", "RESENTS"],
    conflictingKeywords: [],
    possibleAffordances: { DEAL: ["TRADE_INFORMATION"], PRESSURE: ["REVEAL_NONPAYMENT"], ASK: ["REQUEST_EVIDENCE"] },
    blockersAndDefeaters: ["secret_public", "knowledge_expired", "speaker_only_suspects"],
    possibleHistoryEmissions: ["SECRET_LEARNED", "SECRET_DISCLOSED", "SECRET_EXPOSED"],
    positiveExamples: ["Marcus knows a secret about the player's unregistered sublet."],
    boundaryExamples: ["Marcus suspects a secret but lacks authored evidence."],
    counterexamples: ["Knowing someone is late is not necessarily a secret."],
  }),
  keyword({
    keywordId: "BELIEVES",
    displayName: "Believes",
    definition: "An entity holds a scoped proposition with an authored confidence that may differ from actual truth.",
    explicitNonMeanings: ["Does not rewrite actual world facts.", "Does not grant knowledge or certainty."],
    category: "BELIEF",
    arity: 2,
    typedArgumentRoles: { subject: "BELIEVER", object: "PROPOSITION" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "BELIEVED_BY reverses the belief holder and proposition; it is not truth evidence by itself.",
    allowedEntityAndResourceTypes: ["ACTOR", "PROPOSITION", "OBLIGATION", "SECRET"],
    temporalityAndHistoryBehavior: "Beliefs can be revised by authored evidence and emit belief-history events.",
    negationDisputeAndBeliefHandling: "False, uncertain, and disputed beliefs never collapse into ACTUAL scope.",
    relatedStats: ["trust", "fear", "respect"],
    compatibleKeywords: ["KNOWS_SECRET_ABOUT", "OWES", "TRUSTS", "FEARS"],
    conflictingKeywords: [],
    possibleAffordances: { DEAL: ["CHALLENGE_DEBT_VALIDITY"], PRESSURE: [], ASK: ["CHALLENGE_DEBT_VALIDITY", "REQUEST_EVIDENCE"] },
    blockersAndDefeaters: ["insufficient_evidence", "belief_revised", "speaker_lacks_scope"],
    possibleHistoryEmissions: ["BELIEF_FORMED", "BELIEF_REVISED", "BELIEF_WEAKENED"],
    positiveExamples: ["The player believes the debt term is 300 USD."],
    boundaryExamples: ["The player suspects a debt is invalid but has low confidence."],
    counterexamples: ["An authored fact without a believer is not BELIEVES."],
  }),
  keyword({
    keywordId: "TRUSTS",
    displayName: "Trusts",
    definition: "A subject has a directional authored expectation that a target or source will act reliably in this context.",
    explicitNonMeanings: ["Does not mean friendship, truth, or guaranteed compliance.", "Does not arise from a role label alone."],
    category: "EMOTION",
    arity: 2,
    typedArgumentRoles: { subject: "TRUSTER", object: "TRUSTED_TARGET" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "TRUSTED_BY reverses the direction; trust is not automatically reciprocal.",
    allowedEntityAndResourceTypes: ["ACTOR", "RESOURCE", "INFORMATION_SOURCE"],
    relatedStats: ["trust", "familiarity", "respect"],
    compatibleKeywords: ["DEPENDS_ON", "PROMISED_TO", "NEEDS", "BELIEVES"],
    conflictingKeywords: ["RESENTS"],
    possibleAffordances: { DEAL: ["RENEGOTIATE_TERMS"], PRESSURE: [], ASK: ["REQUEST_EXTENSION", "REQUEST_ACCESS"] },
    blockersAndDefeaters: ["trust_broken", "contrary_evidence", "relationship_ended"],
    possibleHistoryEmissions: ["TRUST_EXTENDED", "TRUST_REVISED"],
    positiveExamples: ["The player trusts Imani to keep the disclosure private."],
    boundaryExamples: ["A one-time successful action is evidence, not a trust fact."],
    counterexamples: ["A friendly Vibe cannot create trust."],
  }),
  keyword({
    keywordId: "FEARS",
    displayName: "Fears",
    definition: "A subject has an authored, directional vulnerability response toward a target, consequence, or exposure.",
    explicitNonMeanings: ["Does not prove the feared consequence will occur.", "Does not grant the target a right to coerce."],
    category: "EMOTION",
    arity: 2,
    typedArgumentRoles: { subject: "VULNERABLE_ACTOR", object: "TARGET_OR_CONSEQUENCE" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "FEARED_BY reverses the evidence relation; fear is not reciprocal.",
    allowedEntityAndResourceTypes: ["ACTOR", "PROPOSITION", "RESOURCE", "SECRET"],
    relatedStats: ["fear", "leverage", "resentment"],
    compatibleKeywords: ["HAS_LEVERAGE_OVER", "PROHIBITED", "KNOWS_SECRET_ABOUT", "DEPENDS_ON"],
    conflictingKeywords: [],
    possibleAffordances: { DEAL: ["OFFER_CASH_FOR_EXTENSION"], PRESSURE: ["INVOKE_CONSEQUENCE"], ASK: [] },
    blockersAndDefeaters: ["fear_resolved", "consequence_impossible", "false_belief_corrected"],
    possibleHistoryEmissions: ["FEAR_ACTIVATED", "FEAR_REVISED"],
    positiveExamples: ["The player fears public exposure of the secret."],
    boundaryExamples: ["A risk calculation is not a fear fact unless authored."],
    counterexamples: ["A threatening template does not create FEARS."],
  }),
  keyword({
    keywordId: "RESENTS",
    displayName: "Resents",
    definition: "A subject has an authored grievance toward a target or event tied to a perceived wrong or burden.",
    explicitNonMeanings: ["Does not mean hatred or an inevitable action.", "Does not follow automatically from owing money."],
    category: "EMOTION",
    arity: 2,
    typedArgumentRoles: { subject: "GRIEVING_ACTOR", object: "TARGET_OR_EVENT" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "RESENTED_BY reverses the direction; resentment is not symmetric.",
    allowedEntityAndResourceTypes: ["ACTOR", "EVENT", "OBLIGATION", "RESOURCE"],
    relatedStats: ["resentment", "trust", "respect"],
    compatibleKeywords: ["OWES", "BELIEVES", "FEARS", "HAS_LEVERAGE_OVER"],
    conflictingKeywords: ["TRUSTS"],
    possibleAffordances: { DEAL: ["CHALLENGE_DEBT_VALIDITY"], PRESSURE: ["INVOKE_CONSEQUENCE"], ASK: ["REQUEST_EVIDENCE"] },
    blockersAndDefeaters: ["grievance_addressed", "target_unidentified", "evidence_retracted"],
    possibleHistoryEmissions: ["GRIEVANCE_RECORDED", "GRIEVANCE_RESOLVED"],
    positiveExamples: ["The player resents Marcus's late-added fee."],
    boundaryExamples: ["Disagreeing with a term is not automatically resentment."],
    counterexamples: ["A Condemning Vibe does not create resentment."],
  }),
  keyword({
    keywordId: "HAS_LEVERAGE_OVER",
    displayName: "Has leverage over",
    definition: "A holder has an authored, attributable source of influence over a target's available choices.",
    explicitNonMeanings: ["Does not mean coercion is legal or effective.", "Does not exist without a cited basis such as debt, control, or secret."],
    category: "LEVERAGE",
    arity: 3,
    typedArgumentRoles: { subject: "LEVERAGE_HOLDER", object: "TARGET", term: "LEVERAGE_BASIS" },
    directionality: "DIRECTED",
    inverseOrReciprocalRule: "LEVERAGED_BY reverses holder and target but not the basis or strength.",
    allowedEntityAndResourceTypes: ["ACTOR", "OBLIGATION", "SECRET", "RESOURCE", "PROPOSITION"],
    temporalityAndHistoryBehavior: "Leverage expires or weakens when its basis is fulfilled, exposed, disproven, or revoked; history records the change.",
    relatedStats: ["leverage", "fear", "control", "obligation"],
    compatibleKeywords: ["OWES", "CONTROLS", "KNOWS_SECRET_ABOUT", "FEARS", "PROHIBITED"],
    conflictingKeywords: [],
    possibleAffordances: { DEAL: ["TRADE_INFORMATION", "OFFER_CASH_FOR_EXTENSION"], PRESSURE: ["INVOKE_CONSEQUENCE", "REVEAL_NONPAYMENT"], ASK: [] },
    blockersAndDefeaters: ["basis_expired", "basis_public", "basis_unproven", "target_no_longer_depends"],
    possibleHistoryEmissions: ["LEVERAGE_ESTABLISHED", "LEVERAGE_WEAKENED", "LEVERAGE_LOST"],
    positiveExamples: ["Marcus has leverage over the player because the active debt and secret are authored."],
    boundaryExamples: ["A rumor is only a suspected basis, not established leverage."],
    counterexamples: ["A Vibe named Extortive does not create leverage."],
  }),
]);

export const KEYWORD_BY_ID = new Map(KEYWORDS.map((entry) => [entry.keywordId, entry]));
export const KEYWORD_IDS = Object.freeze(KEYWORDS.map((entry) => entry.keywordId));

export const CROSS_KEYWORD_RULES = Object.freeze([
  { ruleId: "RULE_DEBT_RELIEF", keywords: ["OWES", "NEEDS", "PROMISED_TO"], result: "REQUEST_EXTENSION_OR_REPAYMENT_DEAL" },
  { ruleId: "RULE_RESOURCE_OFFER", keywords: ["OWES", "OWNS", "NEEDS"], result: "OFFER_PARTIAL_PAYMENT" },
  { ruleId: "RULE_CONTROLLED_PERMISSION", keywords: ["CONTROLS", "PERMITTED", "DEPENDS_ON"], result: "REQUEST_ACCESS" },
  { ruleId: "RULE_CONTROLLED_DEFEATER", keywords: ["CONTROLS", "PROHIBITED", "FEARS"], result: "BLOCK_ACCESS_OR_REQUIRE_REVIEW" },
  { ruleId: "RULE_SECRET_LEVERAGE", keywords: ["KNOWS_SECRET_ABOUT", "HAS_LEVERAGE_OVER"], result: "TRADE_INFORMATION_OR_PRESSURE" },
  { ruleId: "RULE_VULNERABILITY_PRESSURE", keywords: ["HAS_LEVERAGE_OVER", "FEARS", "PROHIBITED"], result: "INVOKE_AUTHORED_CONSEQUENCE" },
  { ruleId: "RULE_CONFLICTING_BELIEF", keywords: ["BELIEVES", "OWES", "KNOWS_SECRET_ABOUT"], result: "REQUEST_EVIDENCE_OR_CHALLENGE" },
  { ruleId: "RULE_TRUSTED_DEPENDENCY", keywords: ["TRUSTS", "DEPENDS_ON", "PROMISED_TO"], result: "REQUEST_SUPPORT" },
  { ruleId: "RULE_GRIEVANCE_REVIEW", keywords: ["RESENTS", "OWES", "BELIEVES"], result: "CHALLENGE_DEBT_VALIDITY" },
  { ruleId: "RULE_SECRET_TRUST_TENSION", keywords: ["KNOWS_SECRET_ABOUT", "TRUSTS", "HAS_LEVERAGE_OVER"], result: "TRADE_INFORMATION_WITH_SCOPE" },
  { ruleId: "RULE_NEED_PROVIDER", keywords: ["NEEDS", "DEPENDS_ON", "TRUSTS"], result: "REQUEST_SUPPORT_OR_ACCESS" },
  { ruleId: "RULE_PROMISE_GRIEVANCE", keywords: ["PROMISED_TO", "OWES", "RESENTS"], result: "RENEGOTIATE_OR_CHALLENGE" },
  { ruleId: "RULE_OWNER_ACCESS", keywords: ["OWNS", "CONTROLS", "PERMITTED"], result: "REQUEST_ACCESS_WITH_AUTHORITY" },
]);

export function validateKeywordDefinition(entry) {
  const required = [
    "keywordId", "displayName", "definition", "explicitNonMeanings", "category", "arity",
    "typedArgumentRoles", "directionality", "inverseOrReciprocalRule", "allowedEntityAndResourceTypes",
    "temporalityAndHistoryBehavior", "negationDisputeAndBeliefHandling", "requiredAndForbiddenContexts",
    "relatedStats", "compatibleKeywords", "conflictingKeywords", "possibleAffordances",
    "blockersAndDefeaters", "possibleHistoryEmissions", "sourceAndProjectProvenance", "positiveExamples",
    "boundaryExamples", "counterexamples", "schemaVersion", "reviewStatus",
  ];
  const errors = required.filter((key) => !(key in entry));
  if (!Number.isInteger(entry.arity) || entry.arity < 2 || entry.arity > 3) errors.push("arity");
  if (!KEYWORD_CATEGORIES.includes(entry.category)) errors.push("category");
  if (!entry.typedArgumentRoles || Object.keys(entry.typedArgumentRoles).length !== entry.arity) errors.push("typedArgumentRoles");
  for (const act of ["DEAL", "PRESSURE", "ASK"]) {
    if (!Array.isArray(entry.possibleAffordances?.[act])) errors.push(`possibleAffordances.${act}`);
  }
  if (entry.reviewStatus !== "APPROVED") errors.push("reviewStatus");
  return errors;
}

export function validateKeywordSet(entries = KEYWORDS) {
  const errors = [];
  if (entries.length < 10 || entries.length > 20) errors.push("keyword_count_out_of_range");
  const ids = entries.map((entry) => entry.keywordId);
  if (new Set(ids).size !== ids.length) errors.push("duplicate_keyword_id");
  entries.forEach((entry) => validateKeywordDefinition(entry).forEach((error) => errors.push(`${entry.keywordId}:${error}`)));
  const connectionCounts = Object.fromEntries(entries.map((entry) => [entry.keywordId, CROSS_KEYWORD_RULES.filter((rule) => rule.keywords.includes(entry.keywordId)).length]));
  Object.entries(connectionCounts).forEach(([id, count]) => { if (count < 2) errors.push(`${id}:insufficient_cross_keyword_connections`); });
  return errors;
}
